---
# tasks file for roles/vector-role

- name: Create install dir
  ansible.builtin.file:
    path: "{{ vector_install_dir }}"
    state: directory
  become: true
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-0.35.0-1.x86_64.rpm"
    dest: "{{ vector_install_dir }}/vector-0.35.0-1.x86_64.rpm"
  become: true
- name: Install vector packages
  ansible.builtin.yum:
    name: "{{ vector_install_dir }}/vector-0.35.0-1.x86_64.rpm"
  become: true
  notify: Start vector service
- name: Generate vector.yaml
  template: src=vector.toml.j2 dest={{ vector_config }}
  become: true
  notify: Start vector service
