- name: NGINX | Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: NGINX | Install nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Start Nginx
- name: NGINX | Generate nginx.conf
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx.conf }}/nginx.conf"
    mode: 0644
  notify: Nginx reload