---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

clickhouse_data:
  db: nginxdb
  table: nginxdb.access_logs
  
ansible_ssh_user: centos

